# -*- coding: utf-8 -*-
"""Snippets: Importing libraries

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/snippets/importing_libraries.ipynb
"""

# Installation des bibliothèques
!pip install gspread pandas numpy plotly faker dash dash-bootstrap-components jupyter-dash -q

# Imports
import pandas as pd
import numpy as np
from datetime import datetime, timedelta
import random
from faker import Faker
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import plotly.io as pio
import warnings
warnings.filterwarnings('ignore')

#   thème Plotly
pio.templates.default = "plotly_white"

fake = Faker('fr_FR')
print("✅ Bibliothèques importées")

# ID GOOGLE SHEET
SHEET_ID = '1xeEFBp6bFattjzhvgcP8jSNR1p4UrGQHXTudVs58n2c'  # VOTRE ID ICI

try:
    # Ouvrir le sheet
    spreadsheet = gc.open_by_key(SHEET_ID)
    worksheet = spreadsheet.sheet1

    # Lire les données
    data = worksheet.get_all_values()

    # Créer DataFrame original
    df_original = pd.DataFrame(data[1:], columns=data[0])

    # Nettoyage des colonnes
    df_original.columns = df_original.columns.str.strip().str.replace('\n', ' ')

    print(f"✅ Données chargées : {len(df_original)} réponses")
    print("\nColonnes :")
    for i, col in enumerate(df_original.columns, 1):
        print(f"  {i}. {col}")

except Exception as e:
    print(f"❌ Erreur : {e}")
    print("\n⚠️ Vérifiez que :")
    print("  1. Le sheet est partagé avec votre compte Google")
    print("  2. L'ID du sheet est correct")

# Mapping des colonnes
column_mapping = {
    'Timestamp': 'Timestamp',
    'date voyage': 'Date_voyage',
    'ligne du voyage': 'Ligne',
    'Type de Train': 'Type_Train',
    'retard': 'Retard',
    'satisfaction': 'Satisfaction',
    'Propreté du train': 'Proprete_Train',
    'Propreté des toilettes': 'Proprete_Toilettes',
    'Confort des sièges': 'Confort_Sieges',
    'Climatisation / température': 'Climatisation',
    'Respect du temps': 'Respect_Temps',
    'Quels problèmes avez-vous rencontrés': 'Problemes',
    'Recommanderiez-vous l\'ONCF à un proche': 'Recommandation'
}

# Appliquer le mapping
df_original = df_original.rename(columns=column_mapping)

# Conversion des types
note_columns = ['Satisfaction', 'Proprete_Train', 'Proprete_Toilettes',
                'Confort_Sieges', 'Climatisation', 'Respect_Temps']

for col in note_columns:
    df_original[col] = pd.to_numeric(df_original[col], errors='coerce')

df_original['Date_voyage'] = pd.to_datetime(df_original['Date_voyage'], errors='coerce')
df_original['Timestamp'] = pd.to_datetime(df_original['Timestamp'], errors='coerce')

print("✅ Données nettoyées")
print(f"Réponses : {len(df_original)}")

# Paramètres
NB_TOTAL = 100
NB_ORIGINAL = len(df_original)
NB_SYNTHETIC = NB_TOTAL - NB_ORIGINAL

# Période : 3 janvier au 9 mai 2026
DATE_DEBUT = datetime(2026, 1, 3)
DATE_FIN = datetime(2026, 5, 9)

print(f"📊 Génération de {NB_SYNTHETIC} réponses synthétiques...")

# Configuration des données synthétiques
lignes = [
    'Rabat-Casablanca', 'Casablanca-Marrakech', 'Rabat-Tanger',
    'Rabat-Meknes', 'Rabat-Fes', 'Casablanca-Fes',
    'Marrakech-Fes', 'Tanger-Casablanca', 'Casablanca-Rabat',
    'Marrakech-Casablanca', 'Fes-Tanger', 'Meknes-Rabat'
]

types_train = ['TNR', 'TGV', 'Al Atlas', 'Navette']
problemes_list = [
    'Aucun problème', 'Propreté insuffisante', 'Climatisation défaillante',
    'Retard', 'Personnel désagréable', 'Sièges inconfortables',
    'Manque d\'information', 'Toilettes sales', 'Bruit excessif',
    'Wifi défaillant', 'Portes défectueuses', 'Éclairage insuffisant'
]

def generate_synthetic_data(n):
    """Génère n réponses synthétiques"""
    random.seed(42)
    np.random.seed(42)

    data = []

    for _ in range(n):
        # Timestamp aléatoire
        delta_seconds = random.randint(0, int((DATE_FIN - DATE_DEBUT).total_seconds()))
        timestamp = DATE_DEBUT + timedelta(seconds=delta_seconds)

        # Date voyage (1-30 jours avant le timestamp)
        date_voyage = timestamp - timedelta(days=random.randint(1, 30))

        # Choix aléatoires
        ligne = random.choice(lignes)
        train = random.choice(types_train)

        # 25% de chance de retard
        retard = 'Oui' if random.random() < 0.25 else 'Non'

        # Génération des notes (plus réaliste)
        if train == 'TGV':
            base = np.random.choice([4, 5, 3, 4], p=[0.4, 0.3, 0.2, 0.1])
        elif train == 'Al Atlas':
            base = np.random.choice([3, 4, 2, 3], p=[0.3, 0.4, 0.1, 0.2])
        elif train == 'TNR':
            base = np.random.choice([3, 2, 4, 3], p=[0.3, 0.2, 0.2, 0.3])
        else:  # Navette
            base = np.random.choice([2, 3, 1, 4], p=[0.2, 0.3, 0.1, 0.4])

        # Notes avec variation
        satisfaction = min(5, max(1, base + random.randint(-1, 2)))
        proprete = min(5, max(1, base + random.randint(-1, 1)))
        toilettes = min(5, max(1, base + random.randint(-2, 1)))
        confort = min(5, max(1, base + random.randint(-1, 2)))
        climatisation = min(5, max(1, base + random.randint(-2, 2)))
        respect_temps = min(5, max(1, 5 - random.randint(0, 2) if retard == 'Non' else random.randint(1, 3)))

        # Problèmes
        if satisfaction >= 4 and retard == 'Non' and random.random() < 0.7:
            problemes = 'Aucun problème'
        else:
            nb_problemes = random.randint(1, 3)
            probs = random.sample(problemes_list[1:], min(nb_problemes, len(problemes_list)-1))
            problemes = ';'.join(probs)

        # Recommandation
        if satisfaction >= 4:
            recommandation = 'Oui' if random.random() < 0.9 else 'Non'
        elif satisfaction == 3:
            recommandation = 'Oui' if random.random() < 0.5 else 'Non'
        else:
            recommandation = 'Non' if random.random() < 0.8 else 'Oui'

        data.append([
            timestamp.strftime('%Y/%m/%d %I:%M:%S %p GMT+1'),
            date_voyage.strftime('%Y-%m-%d'),
            ligne, train, retard,
            satisfaction, proprete, toilettes, confort,
            climatisation, respect_temps, problemes, recommandation
        ])

    return data

# Génération
synthetic_data = generate_synthetic_data(NB_SYNTHETIC)
columns = df_original.columns.tolist()
df_synthetic = pd.DataFrame(synthetic_data, columns=columns)

# Conversion types
df_synthetic['Date_voyage'] = pd.to_datetime(df_synthetic['Date_voyage'])
df_synthetic['Timestamp'] = pd.to_datetime(df_synthetic['Timestamp'])
for col in note_columns:
    df_synthetic[col] = pd.to_numeric(df_synthetic[col])

print(f"✅ {len(df_synthetic)} réponses synthétiques générées")

# Fusion des datasets
df_complet = pd.concat([df_original, df_synthetic], ignore_index=True)

print("=" * 50)
print("✅ DATASET COMPLET PRÊT")
print("=" * 50)
print(f"Total réponses : {(df_complet)}")

# Création  HTML complet pour le dashboard
def create_dashboard_html(df):
    "

    # ===== CALCUL DES KPI =====
    total_responses = len(df)
    satisfaction_moy = float(df['Satisfaction'].mean())
    taux_recommandation = float((df['Recommandation'] == 'Oui').mean() * 100)
    taux_retard = float((df['Retard'] == 'Oui').mean() * 100)

    # Distribution satisfaction
    dist_satisfaction = df['Satisfaction'].value_counts().sort_index()

    # Satisfaction par ligne
    satisfaction_ligne = df.groupby('Ligne')['Satisfaction'].mean().round(2)

    # Notes moyennes par catégorie
    note_columns = ['Satisfaction', 'Proprete_Train', 'Proprete_Toilettes',
                    'Confort_Sieges', 'Climatisation', 'Respect_Temps']

    # Analyse problèmes
    problemes_all = ';'.join(df['Problemes'].dropna().astype(str))
    problemes_series = pd.Series(problemes_all.split(';'))
    # Nettoyer les espaces
    problemes_series = problemes_series.str.strip()
    problemes_counts = problemes_series.value_counts().head(5)

    # Évolution temporelle
    df_temp = df.copy()
    df_temp['Mois'] = pd.to_datetime(df_temp['Date_voyage']).dt.strftime('%Y-%m')
    evolution = df_temp.groupby('Mois')['Satisfaction'].mean().round(2)

    # ===== CRÉATION DES GRAPHIQUES =====

    # Graphique 1 : Distribution satisfaction
    notes_labels = ['1 - Très\ninsatisfait', '2 - Insatisfait', '3 - Neutre',
                    '4 - Satisfait', '5 - Très\nsatisfait']
    notes_values = [int(dist_satisfaction.get(i, 0)) for i in range(1, 6)]
    couleurs_notes = ['#E76F51', '#F4A261', '#E9C46A', '#2A9D8F', '#264653']

    fig1 = go.Figure()
    fig1.add_trace(go.Bar(
        x=notes_labels,
        y=notes_values,
        marker_color=couleurs_notes,
        text=notes_values,
        textposition='outside',
        textfont=dict(size=14, color='black'),
        hovertemplate='Note: %{x}<br>Nombre: %{y}<extra></extra>'
    ))
    fig1.update_layout(
        title=dict(
            text='Distribution des Notes de Satisfaction',
            font=dict(size=18, color='#333'),
            x=0.5
        ),
        xaxis_title='Niveau de Satisfaction',
        yaxis_title='Nombre de Voyageurs',
        showlegend=False,
        plot_bgcolor='white',
        paper_bgcolor='white',
        height=450,
        margin=dict(t=60, b=80, l=60, r=30),
        xaxis=dict(tickfont=dict(size=11)),
        yaxis=dict(tickfont=dict(size=12))
    )

    # Graphique 2 : Camembert trains
    train_counts = df['Type_Train'].value_counts()
    couleurs_train = {'TGV': '#E63946', 'Al Atlas': '#2A9D8F',
                      'TNR': '#E9C46A', 'Navette': '#264653'}

    fig2 = go.Figure(data=[go.Pie(
        labels=train_counts.index.tolist(),
        values=train_counts.values.tolist(),
        hole=0.4,
        marker=dict(colors=[couleurs_train.get(t, '#999') for t in train_counts.index]),
        textinfo='label+percent',
        textfont=dict(size=12),
        hovertemplate='%{label}<br>%{value} réponses (%{percent})<extra></extra>'
    )])
    fig2.update_layout(
        title=dict(
            text='Répartition par Type de Train',
            font=dict(size=18, color='#333'),
            x=0.5
        ),
        height=450,
        margin=dict(t=60, b=30, l=30, r=30),
        showlegend=True,
        legend=dict(x=0.8, y=1)
    )

    # Graphique 3 : Radar
    categories_radar = ['Satisfaction', 'Propreté<br>Train', 'Propreté<br>Toilettes',
                        'Confort<br>Sièges', 'Climatisation', 'Respect<br>Temps']
    moyennes_radar = [float(df[col].mean()) for col in note_columns]

    fig3 = go.Figure()
    fig3.add_trace(go.Scatterpolar(
        r=moyennes_radar + [moyennes_radar[0]],  # Fermer le polygone
        theta=categories_radar + [categories_radar[0]],
        fill='toself',
        fillcolor='rgba(230, 57, 70, 0.3)',
        marker=dict(color='#E63946', size=8),
        line=dict(color='#C1121F', width=3),
        name='Note Moyenne',
        hovertemplate='%{theta}: %{r:.2f}/5<extra></extra>'
    ))
    fig3.update_layout(
        polar=dict(
            radialaxis=dict(
                visible=True,
                range=[0, 5],
                tickfont=dict(size=11),
                gridcolor='#ddd'
            ),
            angularaxis=dict(
                tickfont=dict(size=12, color='#333'),
                gridcolor='#ddd'
            )
        ),
        title=dict(
            text='Notes Moyennes par Critère (sur 5)',
            font=dict(size=18, color='#333'),
            x=0.5
        ),
        showlegend=False,
        height=500,
        margin=dict(t=60, b=40, l=40, r=40)
    )

    # Graphique 4 : Problèmes (horizontal)
    problemes_labels = problemes_counts.index.tolist()[::-1]
    problemes_vals = problemes_counts.values.tolist()[::-1]

    fig4 = go.Figure()
    fig4.add_trace(go.Bar(
        y=problemes_labels,
        x=problemes_vals,
        orientation='h',
        marker=dict(
            color='#E76F51',
            line=dict(color='#C1121F', width=1)
        ),
        text=problemes_vals,
        textposition='outside',
        textfont=dict(size=13, color='black'),
        hovertemplate='%{y}: %{x} occurrences<extra></extra>'
    ))
    fig4.update_layout(
        title=dict(
            text='Top 5 Problèmes Rencontrés',
            font=dict(size=18, color='#333'),
            x=0.5
        ),
        xaxis_title='Nombre d\'occurrences',
        plot_bgcolor='white',
        paper_bgcolor='white',
        height=380,
        margin=dict(t=60, b=40, l=200, r=60),
        xaxis=dict(tickfont=dict(size=12)),
        yaxis=dict(tickfont=dict(size=12))
    )

    # Graphique 5 : Satisfaction par ligne
    fig5 = go.Figure()
    fig5.add_trace(go.Bar(
        x=satisfaction_ligne.index.tolist(),
        y=satisfaction_ligne.values.tolist(),
        marker=dict(
            color='#2A9D8F',
            line=dict(color='#1D7A6F', width=1)
        ),
        text=[f'{v:.2f}' for v in satisfaction_ligne.values],
        textposition='outside',
        textfont=dict(size=12, color='black'),
        hovertemplate='Ligne: %{x}<br>Note: %{y:.2f}/5<extra></extra>'
    ))
    fig5.update_layout(
        title=dict(
            text='Satisfaction Moyenne par Ligne',
            font=dict(size=18, color='#333'),
            x=0.5
        ),
        xaxis_title='Ligne',
        yaxis_title='Note Moyenne /5',
        yaxis=dict(range=[1, 5], tickfont=dict(size=12)),
        xaxis=dict(tickfont=dict(size=10), tickangle=45),
        plot_bgcolor='white',
        paper_bgcolor='white',
        height=450,
        margin=dict(t=60, b=120, l=60, r=40)
    )

    # Graphique 6 : Évolution temporelle
    fig6 = go.Figure()
    fig6.add_trace(go.Scatter(
        x=evolution.index.tolist(),
        y=evolution.values.tolist(),
        mode='lines+markers+text',
        marker=dict(size=14, color='#E63946', line=dict(color='white', width=2)),
        line=dict(width=4, color='#C1121F'),
        text=[f'{v:.2f}' for v in evolution.values],
        textposition='top center',
        textfont=dict(size=13, color='#333'),
        hovertemplate='Mois: %{x}<br>Note: %{y:.2f}/5<extra></extra>'
    ))
    fig6.update_layout(
        title=dict(
            text='Évolution Mensuelle de la Satisfaction',
            font=dict(size=18, color='#333'),
            x=0.5
        ),
        xaxis_title='Mois',
        yaxis_title='Note Moyenne /5',
        plot_bgcolor='white',
        paper_bgcolor='white',
        height=450,
        margin=dict(t=60, b=60, l=60, r=40),
        xaxis=dict(tickfont=dict(size=12)),
        yaxis=dict(tickfont=dict(size=12))
    )

    # Conversion en HTML individuel (IMPORTANT: include_plotlyjs une seule fois)
    graph1_html = pio.to_html(fig1, full_html=False, include_plotlyjs='cdn')
    graph2_html = pio.to_html(fig2, full_html=False, include_plotlyjs=False)
    graph3_html = pio.to_html(fig3, full_html=False, include_plotlyjs=False)
    graph4_html = pio.to_html(fig4, full_html=False, include_plotlyjs=False)
    graph5_html = pio.to_html(fig5, full_html=False, include_plotlyjs=False)
    graph6_html = pio.to_html(fig6, full_html=False, include_plotlyjs=False)

    # ===== TABLEAU RÉCAPITULATIF =====
    tableau_rows = ""
    for train in sorted(df['Type_Train'].unique()):
        df_train = df[df['Type_Train'] == train]
        sat_mean = float(df_train['Satisfaction'].mean())
        couleur = '#2A9D8F' if sat_mean >= 3.5 else '#E76F51'

        tableau_rows += f"""
        <tr>
            <td style="text-align: left; padding-left: 20px;">
                <strong>🚂 {train}</strong>
            </td>
            <td>
                <span class="badge-note" style="background: {couleur};">
                    {sat_mean:.1f}
                </span>
            </td>
            <td>{float(df_train['Proprete_Train'].mean()):.2f}</td>
            <td>{float(df_train['Confort_Sieges'].mean()):.2f}</td>
            <td>{float(df_train['Climatisation'].mean()):.2f}</td>
            <td>{float(df_train['Respect_Temps'].mean()):.2f}</td>
        </tr>"""

    # ===== HTML COMPLET =====
    html_page = f"""<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ONCF - Dashboard Satisfaction Voyageurs 2026</title>
    <style>
        * {{
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }}

        body {{
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            background: #f0f2f5;
            min-height: 100vh;
        }}

        .dashboard-container {{
            max-width: 1400px;
            margin: 0 auto;
            padding: 20px;
        }}

        /* HEADER */
        .header {{
            background: linear-gradient(135deg, #E63946 0%, #C1121F 100%);
            color: white;
            padding: 40px;
            border-radius: 20px;
            margin-bottom: 30px;
            text-align: center;
            box-shadow: 0 10px 40px rgba(230, 57, 70, 0.3);
        }}

        .header .logo {{
            font-size: 4em;
            margin-bottom: 10px;
        }}

        .header h1 {{
            font-size: 2.5em;
            margin-bottom: 10px;
            font-weight: 700;
        }}

        .header .subtitle {{
            font-size: 1.1em;
            opacity: 0.95;
        }}

        /* KPIs */
        .kpi-grid {{
            display: grid;
            grid-template-columns: repeat(4, 1fr);
            gap: 20px;
            margin-bottom: 30px;
        }}

        .kpi-card {{
            background: white;
            padding: 30px 20px;
            border-radius: 15px;
            text-align: center;
            box-shadow: 0 4px 15px rgba(0,0,0,0.08);
            transition: all 0.3s ease;
            cursor: default;
        }}

        .kpi-card:hover {{
            transform: translateY(-5px);
            box-shadow: 0 8px 25px rgba(0,0,0,0.15);
        }}

        .kpi-icon {{
            font-size: 3em;
            margin-bottom: 15px;
        }}

        .kpi-value {{
            font-size: 2.8em;
            font-weight: 700;
            color: #E63946;
            margin: 10px 0;
        }}

        .kpi-label {{
            font-size: 1em;
            color: #555;
            font-weight: 600;
            text-transform: uppercase;
            letter-spacing: 1px;
        }}

        .kpi-subtitle {{
            font-size: 0.8em;
            color: #999;
            margin-top: 5px;
        }}

        /* GRAPHS */
        .graph-grid-2 {{
            display: grid;
            grid-template-columns: 1fr 1fr;
            gap: 20px;
            margin-bottom: 20px;
        }}

        .graph-grid-1 {{
            display: grid;
            grid-template-columns: 1fr;
            gap: 20px;
            margin-bottom: 20px;
        }}

        .graph-card {{
            background: white;
            padding: 25px;
            border-radius: 15px;
            box-shadow: 0 4px 15px rgba(0,0,0,0.08);
            transition: transform 0.3s ease;
        }}

        .graph-card:hover {{
            transform: translateY(-3px);
            box-shadow: 0 8px 25px rgba(0,0,0,0.12);
        }}

        /* TABLE */
        .section-title {{
            text-align: center;
            color: #333;
            margin-bottom: 25px;
            font-size: 1.6em;
            font-weight: 700;
        }}

        table {{
            width: 100%;
            border-collapse: collapse;
            margin-top: 15px;
        }}

        thead tr {{
            background: linear-gradient(135deg, #E63946, #C1121F);
            color: white;
        }}

        th {{
            padding: 16px 15px;
            text-align: center;
            font-weight: 600;
            text-transform: uppercase;
            font-size: 0.85em;
            letter-spacing: 0.5px;
        }}

        td {{
            padding: 14px 15px;
            text-align: center;
            border-bottom: 1px solid #eee;
            font-size: 1em;
        }}

        tbody tr:hover {{
            background: #f8f9fa;
        }}

        .badge-note {{
            display: inline-block;
            width: 40px;
            height: 40px;
            border-radius: 50%;
            line-height: 40px;
            color: white;
            font-weight: 700;
            font-size: 1.1em;
        }}

        /* FOOTER */
        .footer {{
            background: white;
            padding: 25px;
            border-radius: 15px;
            text-align: center;
            margin-top: 30px;
            color: #666;
            box-shadow: 0 4px 15px rgba(0,0,0,0.08);
        }}

        .footer p {{
            margin: 5px 0;
        }}

        /* RESPONSIVE */
        @media (max-width: 1200px) {{
            .kpi-grid {{
                grid-template-columns: repeat(2, 1fr);
            }}
            .graph-grid-2 {{
                grid-template-columns: 1fr;
            }}
        }}

        @media (max-width: 768px) {{
            .kpi-grid {{
                grid-template-columns: 1fr;
            }}
            .header h1 {{
                font-size: 1.5em;
            }}
            .kpi-value {{
                font-size: 2em;
            }}
        }}
    </style>
</head>
<body>
    <div class="dashboard-container">

        <!-- HEADER -->
        <div class="header">
            <div class="logo">🚂</div>
            <h1>ONCF - Tableau de Bord Satisfaction Voyageurs</h1>
            <p class="subtitle">
                📅 Période : <strong>{df['Date_voyage'].min().strftime('%d/%m/%Y')}</strong>
                → <strong>{df['Date_voyage'].max().strftime('%d/%m/%Y')}</strong>
                &nbsp;|&nbsp; 📊 <strong>{total_responses} réponses</strong> collectées
            </p>
        </div>

        <!-- KPIs -->
        <div class="kpi-grid">
            <div class="kpi-card">
                <div class="kpi-icon">⭐</div>
                <div class="kpi-value">{satisfaction_moy:.2f}<small style="font-size:0.4em;">/5</small></div>
                <div class="kpi-label">Satisfaction</div>
                <div class="kpi-subtitle">Note moyenne globale</div>
            </div>

            <div class="kpi-card">
                <div class="kpi-icon">👍</div>
                <div class="kpi-value">{taux_recommandation:.1f}<small style="font-size:0.4em;">%</small></div>
                <div class="kpi-label">Recommandation</div>
                <div class="kpi-subtitle">Recommanderaient ONCF</div>
            </div>

            <div class="kpi-card">
                <div class="kpi-icon">⏰</div>
                <div class="kpi-value">{taux_retard:.1f}<small style="font-size:0.4em;">%</small></div>
                <div class="kpi-label">Retards</div>
                <div class="kpi-subtitle">Trains signalés en retard</div>
            </div>

            <div class="kpi-card">
                <div class="kpi-icon">👥</div>
                <div class="kpi-value">{total_responses}</div>
                <div class="kpi-label">Répondants</div>
                <div class="kpi-subtitle">Total questionnaires</div>
            </div>
        </div>

        <!-- RANGÉE 1 : 2 Graphiques -->
        <div class="graph-grid-2">
            <div class="graph-card">
                {graph1_html}
            </div>
            <div class="graph-card">
                {graph2_html}
            </div>
        </div>

        <!-- RANGÉE 2 : Radar (pleine largeur) -->
        <div class="graph-grid-1">
            <div class="graph-card">
                {graph3_html}
            </div>
        </div>

        <!-- RANGÉE 3 : 2 Graphiques -->
        <div class="graph-grid-2">
            <div class="graph-card">
                {graph5_html}
            </div>
            <div class="graph-card">
                {graph4_html}
            </div>
        </div>

        <!-- RANGÉE 4 : Évolution (pleine largeur) -->
        <div class="graph-grid-1">
            <div class="graph-card">
                {graph6_html}
            </div>
        </div>

        <!-- TABLEAU RÉCAPITULATIF -->
        <div class="graph-grid-1">
            <div class="graph-card">
                <h2 class="section-title">📊 Récapitulatif Détaillé par Type de Train</h2>
                <div style="overflow-x: auto;">
                    <table>
                        <thead>
                            <tr>
                                <th style="text-align: left; padding-left: 25px;">Type de Train</th>
                                <th>⭐ Satisfaction</th>
                                <th>🧹 Propreté</th>
                                <th>💺 Confort</th>
                                <th>❄️ Climatisation</th>
                                <th>⏱️ Respect Temps</th>
                            </tr>
                        </thead>
                        <tbody>
                            {tableau_rows}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

        <!-- FOOTER -->
        <div class="footer">
            <p><strong>🚂 ONCF - Office National des Chemins de Fer</strong></p>
            <p>Analyse Satisfaction Voyageurs | Dashboard généré le {datetime.now().strftime('%d/%m/%Y à %H:%M')}</p>
            <p style="font-size: 0.8em; margin-top: 10px; color: #aaa;">
                © 2026 ONCF - Tous droits réservés
            </p>
        </div>

    </div>
</body>
</html>"""

    return html_page

# ===== GÉNÉRATION DU DASHBOARD =====
print("🔄 Génération du dashboard HTML optimisé...")
dashboard_html = create_dashboard_html(df_complet)
print("✅ Dashboard HTML créé avec succès !")
print(f"   Taille du HTML : {len(dashboard_html):,} caractères")

# Sauvegarde du fichier HTML
with open('ONCF_Dashboard.html', 'w', encoding='utf-8') as f:
    f.write(dashboard_html)

print("💾 Fichier 'ONCF_Dashboard.html' sauvegardé avec succès !")

# Téléchargement automatique
from google.colab import files
files.download('ONCF_Dashboard.html')
print("\n📥 Le dashboard a été téléchargé !")
print("👉 Ouvrez le fichier 'ONCF_Dashboard.html' dans votre navigateur")